//! The golden generator and byte-exact parity checker.
//!
//! `bless` (re)writes three committed artifacts from the single feed formula:
//! the CSV feed, the embedded `FEED` const, and the expected signal sequence.
//! `check` recomputes the signal sequence and asserts it equals the committed
//! expected byte-for-byte — the host side of the cross-target parity guarantee.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use wickra_pico_signal::SignalEngine;

/// Number of ticks in the replay feed.
pub const FEED_LEN: usize = 128;

/// The deterministic replay feed: a drifting sine wave, computed in `f32`.
///
/// `price(i) = 100 + 15·sin(i/8) + 0.05·i`. The `f32` values widen losslessly to
/// the `f64` the engine consumes, so the host and the device see the same feed.
#[allow(clippy::cast_precision_loss)] // i < 128; the cast is exact enough here
pub fn feed() -> [f32; FEED_LEN] {
    let mut out = [0.0f32; FEED_LEN];
    for (i, slot) in out.iter_mut().enumerate() {
        let x = i as f32;
        // `libm::sinf`, not `f32::sin`: the host libm differs by ~1 ULP across
        // OSes, so a const blessed on one platform would trip the drift guard on
        // another. `libm` is bit-identical everywhere.
        *slot = 100.0 + 15.0 * libm::sinf(x / 8.0) + 0.05 * x;
    }
    out
}

/// Run the signal engine over the feed and render the expected sequence.
///
/// Each fired signal is one `"<index> <token>"` line. Feeding `f64::from(price)`
/// is exactly what the firmware does, so the sequences match.
pub fn run_signals(feed: &[f32]) -> String {
    let mut engine = SignalEngine::new();
    let mut out = String::new();
    for (i, &price) in feed.iter().enumerate() {
        if let Some(sig) = engine.on_tick(f64::from(price)) {
            writeln!(out, "{i} {}", sig.token()).unwrap();
        }
    }
    out
}

/// Render the CSV feed (`index,price`, one row per tick).
fn render_csv(feed: &[f32]) -> String {
    let mut s = String::from("index,price\n");
    for (i, &price) in feed.iter().enumerate() {
        // `{:?}` is the shortest round-tripping f32 repr, so the CSV and the
        // FEED const parse back to identical bits.
        writeln!(s, "{i},{price:?}").unwrap();
    }
    s
}

/// Render the `embedded-data` crate's `FEED` const source.
fn render_embedded_lib(feed: &[f32]) -> String {
    let mut s = String::new();
    s.push_str("//! The embedded replay feed for the Wickra Pico demo.\n//!\n");
    s.push_str(
        "//! GENERATED by `wickra-pico-host bless` from the feed formula — never hand-edit.\n",
    );
    s.push_str("//! Regenerate with `cargo run -p wickra-pico-host -- bless`.\n");
    s.push_str("#![no_std]\n");
    s.push_str("#![allow(clippy::unreadable_literal)] // machine-generated feed literals\n\n");
    writeln!(s, "/// The replay feed: {} price ticks.", feed.len()).unwrap();
    // One literal per line is the canonical bless layout; keep rustfmt from
    // reflowing it so `cargo fmt --check` stays green on this generated file.
    s.push_str("#[rustfmt::skip]\n");
    writeln!(s, "pub const FEED: [f32; {}] = [", feed.len()).unwrap();
    for &price in feed {
        writeln!(s, "    {price:?},").unwrap();
    }
    s.push_str(
        "];\n\n/// The number of ticks in [`FEED`].\npub const FEED_LEN: usize = FEED.len();\n",
    );
    s
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn csv_path() -> PathBuf {
    repo_root()
        .join("golden")
        .join("data")
        .join("ema_cross.csv")
}

/// Path of the committed expected signal sequence.
pub fn expected_path() -> PathBuf {
    repo_root()
        .join("golden")
        .join("expected")
        .join("ema_cross.txt")
}

fn embedded_lib_path() -> PathBuf {
    repo_root().join("embedded-data").join("src").join("lib.rs")
}

/// Regenerate all three committed artifacts from the feed formula.
///
/// # Panics
/// Panics if any artifact cannot be written (the tool is a developer command).
pub fn bless() {
    let feed = feed();
    let csv = csv_path();
    let expected = expected_path();
    fs::create_dir_all(csv.parent().unwrap()).unwrap();
    fs::create_dir_all(expected.parent().unwrap()).unwrap();
    fs::write(&csv, render_csv(&feed)).unwrap();
    fs::write(&expected, run_signals(&feed)).unwrap();
    fs::write(embedded_lib_path(), render_embedded_lib(&feed)).unwrap();
    println!(
        "blessed: {}, {}, embedded-data/src/lib.rs",
        csv.display(),
        expected.display()
    );
}

/// Recompute the signal sequence and compare it to the committed golden.
///
/// Returns [`ExitCode::SUCCESS`] on a byte-exact match, [`ExitCode::FAILURE`]
/// otherwise (with a diff summary on stderr).
#[must_use]
pub fn check() -> ExitCode {
    let produced = run_signals(&feed());
    let committed = match fs::read_to_string(expected_path()) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("cannot read golden expected: {e} — run `bless` first");
            return ExitCode::FAILURE;
        }
    };
    if produced == committed {
        println!(
            "check: signal sequence matches the golden ({} bytes)",
            produced.len()
        );
        ExitCode::SUCCESS
    } else {
        eprintln!("check: signal sequence DIVERGED from the golden");
        eprintln!("--- committed ---\n{committed}--- produced ---\n{produced}");
        ExitCode::FAILURE
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn produced_matches_committed_golden() {
        let produced = super::run_signals(&super::feed());
        let committed = std::fs::read_to_string(super::expected_path())
            .expect("golden/expected/ema_cross.txt — run `bless`");
        assert_eq!(
            produced, committed,
            "run `cargo run -p wickra-pico-host -- bless`"
        );
    }

    #[test]
    fn embedded_feed_matches_formula() {
        // Drift guard: the committed const feed must equal the formula output,
        // bit-for-bit (compare raw bits so an exact match is the assertion).
        let committed = embedded_data::FEED.map(f32::to_bits);
        let formula = super::feed().map(f32::to_bits);
        assert_eq!(committed, formula, "run `bless` — the const feed drifted");
        assert_eq!(embedded_data::FEED_LEN, super::FEED_LEN);
    }

    #[test]
    fn the_csv_is_what_the_embedded_const_parses_back_to() {
        // Both artifacts are rendered from one feed with `{:?}`, the shortest
        // round-tripping f32 form. If either rendering stopped round-tripping,
        // the device and the host would read different prices from artifacts
        // that look the same -- so the CSV is parsed back and compared by bits.
        let feed = super::feed();
        let csv = super::render_csv(&feed);
        let mut lines = csv.lines();
        assert_eq!(
            lines.next(),
            Some("index,price"),
            "the CSV carries a header"
        );

        let mut parsed = Vec::with_capacity(super::FEED_LEN);
        for (i, line) in lines.enumerate() {
            let (index, price) = line.split_once(',').expect("index,price");
            assert_eq!(index.parse::<usize>().expect("an index"), i);
            parsed.push(price.parse::<f32>().expect("a price"));
        }
        assert_eq!(parsed.len(), super::FEED_LEN);
        assert_eq!(
            parsed.iter().map(|p| p.to_bits()).collect::<Vec<_>>(),
            feed.iter().map(|p| p.to_bits()).collect::<Vec<_>>(),
            "the CSV has to parse back to the feed it was rendered from"
        );
    }

    #[test]
    fn the_embedded_source_is_the_committed_one() {
        // `bless` writes this file; the test asserts the renderer still produces
        // exactly what is committed, so a change to the rendering is noticed
        // here rather than in a diff nobody reads.
        let rendered = super::render_embedded_lib(&super::feed());
        let committed =
            std::fs::read_to_string(super::embedded_lib_path()).expect("embedded-data/src/lib.rs");
        // Compared line by line: git may have checked the file out with CRLF,
        // and the line endings are not what this test is about.
        assert!(
            rendered.lines().eq(committed.lines()),
            "run `cargo run -p wickra-pico-host -- bless`"
        );
    }

    #[test]
    fn the_paths_point_inside_the_repository() {
        // Each artifact path is built from CARGO_MANIFEST_DIR; a wrong join
        // would have `bless` write outside the repository, which is the kind of
        // mistake that is only noticed after it happened.
        for path in [
            super::csv_path(),
            super::expected_path(),
            super::embedded_lib_path(),
        ] {
            assert!(path.exists(), "{} is committed", path.display());
            let root = super::repo_root().canonicalize().expect("the repo root");
            assert!(
                path.canonicalize()
                    .expect("the artifact")
                    .starts_with(&root),
                "{} lies inside {}",
                path.display(),
                root.display()
            );
        }
    }

    #[test]
    fn check_succeeds_against_the_committed_golden() {
        // The command the CI parity job runs, exercised as a function: a
        // byte-exact match is SUCCESS.
        assert_eq!(
            format!("{:?}", super::check()),
            format!("{:?}", std::process::ExitCode::SUCCESS)
        );
    }

    #[test]
    fn a_signal_line_is_an_index_and_a_token() {
        let produced = super::run_signals(&super::feed());
        assert!(!produced.is_empty(), "the feed has to fire something");
        for line in produced.lines() {
            let (index, token) = line.split_once(' ').expect("<index> <token>");
            assert!(
                index.parse::<usize>().expect("an index") < super::FEED_LEN,
                "{line}"
            );
            assert!(!token.is_empty(), "{line}");
        }
    }
}
