//! The golden generator and byte-exact parity checker.
//!
//! `bless` (re)writes three committed artifacts from the single feed formula:
//! the CSV feed, the embedded `FEED` const, and the expected signal sequence.
//! `check` recomputes the signal sequence and asserts it equals the committed
//! expected byte-for-byte — the host side of the cross-target parity guarantee.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use wickra_pico_signal::SignalEngine;

/// Number of ticks in the replay feed.
pub const FEED_LEN: usize = 128;

/// The deterministic replay feed: a drifting sine wave, computed in `f32`.
///
/// `price(i) = 100 + 15·sin(i/8) + 0.05·i`. The `f32` values widen losslessly to
/// the `f64` the engine consumes, so the host and the device see the same feed.
#[allow(clippy::cast_precision_loss)] // i < 128; the cast is exact enough here
pub fn feed() -> [f32; FEED_LEN] {
    let mut out = [0.0f32; FEED_LEN];
    for (i, slot) in out.iter_mut().enumerate() {
        let x = i as f32;
        // `libm::sinf`, not `f32::sin`: the host libm differs by ~1 ULP across
        // OSes, so a const blessed on one platform would trip the drift guard on
        // another. `libm` is bit-identical everywhere.
        *slot = 100.0 + 15.0 * libm::sinf(x / 8.0) + 0.05 * x;
    }
    out
}

/// Run the signal engine over the feed and render the expected sequence.
///
/// Each fired signal is one `"<index> <token>"` line. Feeding `f64::from(price)`
/// is exactly what the firmware does, so the sequences match.
pub fn run_signals(feed: &[f32]) -> String {
    let mut engine = SignalEngine::new();
    let mut out = String::new();
    for (i, &price) in feed.iter().enumerate() {
        if let Some(sig) = engine.on_tick(f64::from(price)) {
            writeln!(out, "{i} {}", sig.token()).unwrap();
        }
    }
    out
}

/// Render the CSV feed (`index,price`, one row per tick).
fn render_csv(feed: &[f32]) -> String {
    let mut s = String::from("index,price\n");
    for (i, &price) in feed.iter().enumerate() {
        // `{:?}` is the shortest round-tripping f32 repr, so the CSV and the
        // FEED const parse back to identical bits.
        writeln!(s, "{i},{price:?}").unwrap();
    }
    s
}

/// Render the `embedded-data` crate's `FEED` const source.
fn render_embedded_lib(feed: &[f32]) -> String {
    let mut s = String::new();
    s.push_str("//! The embedded replay feed for the Wickra Pico demo.\n//!\n");
    s.push_str(
        "//! GENERATED by `wickra-pico-host bless` from the feed formula — never hand-edit.\n",
    );
    s.push_str("//! Regenerate with `cargo run -p wickra-pico-host -- bless`.\n");
    s.push_str("#![no_std]\n");
    s.push_str("#![allow(clippy::unreadable_literal)] // machine-generated feed literals\n\n");
    writeln!(s, "/// The replay feed: {} price ticks.", feed.len()).unwrap();
    // One literal per line is the canonical bless layout; keep rustfmt from
    // reflowing it so `cargo fmt --check` stays green on this generated file.
    s.push_str("#[rustfmt::skip]\n");
    writeln!(s, "pub const FEED: [f32; {}] = [", feed.len()).unwrap();
    for &price in feed {
        writeln!(s, "    {price:?},").unwrap();
    }
    s.push_str(
        "];\n\n/// The number of ticks in [`FEED`].\npub const FEED_LEN: usize = FEED.len();\n",
    );
    s
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn csv_path() -> PathBuf {
    repo_root()
        .join("golden")
        .join("data")
        .join("ema_cross.csv")
}

/// Path of the committed expected signal sequence.
pub fn expected_path() -> PathBuf {
    repo_root()
        .join("golden")
        .join("expected")
        .join("ema_cross.txt")
}

fn embedded_lib_path() -> PathBuf {
    repo_root().join("embedded-data").join("src").join("lib.rs")
}

/// Regenerate all three committed artifacts from the feed formula.
///
/// # Panics
/// Panics if any artifact cannot be written (the tool is a developer command).
pub fn bless() {
    let feed = feed();
    let csv = csv_path();
    let expected = expected_path();
    fs::create_dir_all(csv.parent().unwrap()).unwrap();
    fs::create_dir_all(expected.parent().unwrap()).unwrap();
    fs::write(&csv, render_csv(&feed)).unwrap();
    fs::write(&expected, run_signals(&feed)).unwrap();
    fs::write(embedded_lib_path(), render_embedded_lib(&feed)).unwrap();
    println!(
        "blessed: {}, {}, embedded-data/src/lib.rs",
        csv.display(),
        expected.display()
    );
}

/// Recompute the signal sequence and compare it to the committed golden.
///
/// Returns [`ExitCode::SUCCESS`] on a byte-exact match, [`ExitCode::FAILURE`]
/// otherwise (with a diff summary on stderr).
#[must_use]
pub fn check() -> ExitCode {
    let produced = run_signals(&feed());
    let committed = match fs::read_to_string(expected_path()) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("cannot read golden expected: {e} — run `bless` first");
            return ExitCode::FAILURE;
        }
    };
    if produced == committed {
        println!(
            "check: signal sequence matches the golden ({} bytes)",
            produced.len()
        );
        ExitCode::SUCCESS
    } else {
        eprintln!("check: signal sequence DIVERGED from the golden");
        eprintln!("--- committed ---\n{committed}--- produced ---\n{produced}");
        ExitCode::FAILURE
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn produced_matches_committed_golden() {
        let produced = super::run_signals(&super::feed());
        let committed = std::fs::read_to_string(super::expected_path())
            .expect("golden/expected/ema_cross.txt — run `bless`");
        assert_eq!(
            produced, committed,
            "run `cargo run -p wickra-pico-host -- bless`"
        );
    }

    #[test]
    fn embedded_feed_matches_formula() {
        // Drift guard: the committed const feed must equal the formula output,
        // bit-for-bit (compare raw bits so an exact match is the assertion).
        let committed = embedded_data::FEED.map(f32::to_bits);
        let formula = super::feed().map(f32::to_bits);
        assert_eq!(committed, formula, "run `bless` — the const feed drifted");
        assert_eq!(embedded_data::FEED_LEN, super::FEED_LEN);
    }
}
